config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    resources :tasks, only: [:index, :show]
    get '*unmatched_route', to: 'base#raise_not_found'
  end

  resources :tasks do
    resources :comments, only: [:index, :new, :create]
  end

  devise_for :users

  get '/english', to: 'application#set_to_english'
  get '/russian', to: 'application#set_to_russian'

  root 'tasks#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :name, presence: true

  enum status: [:opened, :in_progress, :closed]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, :name, presence: true
  validates_uniqueness_of :name, case_sensitive: false
  validates :email, presence: true, uniqueness: true, format: {with: Devise.email_regexp}

end

app/controllers/api/tasks_controller.rb
module Api
  class TasksController < ApplicationController
    respond_to :json

    def index
      @tasks = Task.all
      fresh_when(etag: @tasks, last_modified: @tasks.maximum(:updated_at))
    end

    def show
      @task = Task.find(params[:id])
      if @task
        fresh_when(etag: @task, last_modified: @task.updated_at)
      end
    rescue
      render json: {id: 'not_found', message: 'Not Found'}, status: 404
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_to_english
    I18n.locale = :en
    set_session_and_redirect
  end

  def set_to_russian
    I18n.locale = :ru
    set_session_and_redirect
  end

  private

  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

  def set_session_and_redirect
    session[:locale] = I18n.locale
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to :root
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:create]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Task.find(params[:task_id]).comments.includes(:user).references(:user)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.js { }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Task.find(params[:task_id]).comments.new(comment_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.page(params[:page])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comment = @task.comments.new
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: t('tasks.messages.created') }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: t('tasks.messages.updated') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: t('tasks.messages.deleted') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :user_id, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/_error_messages.html.slim
#error-container
  /= I18n.t(object.errors.full_messages.to_sentence) if object.errors.full_messages.any?

app/views/application/_flash.html.slim
= content_tag :p, notice, class: 'alert alert-success' if notice.present?
= content_tag :p, alert, class: 'alert alert-danger' if alert.present?

app/views/application/_navbar.html.slim
ul.nav.navbar-top-links.navbar-left
  li
    =link_to t(Task.model_name.human(count: 2)), tasks_path

ul.nav.navbar-top-links.navbar-right
  li
    - if I18n.locale.to_s == 'ru'
      =link_to 'English', english_path
    -else
      =link_to 'Русский', russian_path
ul.nav.navbar-top-links.navbar-right
  li
    -if user_signed_in?
      =link_to t('devise.sessions.log_out'), destroy_user_session_path, method: :delete

app/views/comments/create.js.erb
$('#my-comment').modal('hide');
$('#comment_body').val('');

window.commentBox.loadCommentsFromServer();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div id="wrapper">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Меню</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <%= render 'application/navbar' %>
      </div>
    </div>
  </nav>
  <div id="page-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<div class="row">
  <div class="col-lg-12">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/tasks/_form.html.slim
= simple_form_for(@task, html: { class: 'form-vertical', novalidate: false, role: "form"}) do |f|
  .form-inputs
    = f.input :name
    = f.input :description, as: :text
    = f.input :status, collection: [:opened, :in_progress, :closed], prompt: :translate
    = f.association :user
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn btn-outline btn-default'

app/views/tasks/_result.html.slim
table.table.table-hover
  thead
    tr
      th= model_class.human_attribute_name(:date)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:user)
      th= model_class.human_attribute_name(:status)
      th
      th
      th

  tbody.page
    - @tasks.each do |task|
      tr
        td = task.created_at.strftime('%d.%m.%Y %H:%M')
        td = task.name
        td = task.user.try(:name)
        td = t task.status
        td = link_to t('helpers.links.show'), task_path(task)
        td = link_to t('helpers.links.edit'), edit_task_path(task)
        td = link_to t('helpers.links.destroy'), task, data: {:confirm => t('helpers.links.confirm')}, :method => :delete

= paginate @tasks, remote: true, theme: 'twitter-bootstrap-3'

app/views/tasks/edit.html.slim
- model_class = Task
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        h5= t('helpers.titles.edit', model: Task.model_name.human(count: 3).titleize)
    .panel-body
      .row
        .col-lg-6
          == render 'form'

app/views/tasks/index.html.slim
- model_class = Task
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        h4= t '.title', :default => model_class.model_name.human(count: 2).titleize
      .panel-body
        .table-responsive#result
          ==render partial: 'result', locals: {model_class: model_class}

br

= link_to t('.new', :default => t("helpers.links.new")), new_task_path, class: 'btn btn-primary'

app/views/tasks/index.js.erb
$('#result').html("<%= j(render(partial: "result", locals: {model_class: Task})) %>");

app/views/tasks/new.html.slim
- model_class = Task
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        h5= t('helpers.titles.new', model: model_class.model_name.human.titleize)
    .panel-body
      .row
        .col-lg-6
          == render 'form'

app/views/tasks/show.html.slim
- model_class = Task
== render 'application/flash'
.row
  .col-lg-6
    .panel.panel-default
      .panel-heading
        h5= @task.name
    .panel-body
      .row
        .col-lg-12
          p.bg-info= model_class.human_attribute_name(:date)
          p= @task.created_at.strftime('%d.%m.%Y %H:%M')
      .row
        .col-lg-12
          p.bg-info= model_class.human_attribute_name(:user)
          p= @task.user.try(:name)
      .row
        .col-lg-12
          p.bg-info= model_class.human_attribute_name(:status)
          p= t @task.status
      .row
        .col-lg-12
          p.bg-info= model_class.human_attribute_name(:description)
          p= @task.description
  .col-lg-6
    .panel.panel-default
      .panel-heading
        h5= Comment.model_name.human(count: 2).titleize
    .panel-body
      #comments
hr

.form-actions
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(@task), data: {url: task_path(@task) + '/comments'}, :class => 'btn btn-outline btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.back")), tasks_path, :class => 'btn btn-outline btn-default'
  = link_to t("helpers.links.add_comment"), '#', data: {toggle: "modal", target: "#my-comment"}, :class => 'btn btn-outline btn-default'

#my-comment.modal.fade role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4= t('helpers.titles.comment')
      .modal-body
        = simple_form_for [@task, @comment], :html => {:class => 'form-vertical', role: "form"}, remote: true do |f|
          .form-inputs
            = f.input :body, as: :text, wrapper_html: {class: 'col-lg-12'}, label: false
          .form-actions
            = f.button :submit, class: 'btn-primary'
            = link_to t('.cancel', :default => t("helpers.links.cancel")), '#', :class => 'btn btn-outline btn-default', data: {dismiss: "modal"}
      .modal-footer